#!/bin/bash
timedatectl set-ntp true

#    # # Install systemd-boot to the ESP.
#    # bootctl --no-variables --path=mnt/boot install
#    # 
#    # # Setup the locale.
#    # sed -ie "s/#en_US\.UTF/en_US.UTF/" /etc/locale.gen 
#    # locale-gen
#    # locale
#    # 
#    # # Setup the timezone for correct local system time.
#    # timedatectl set-timezone America/Denver
#    # 
#    # # Set the system clock to use NTP.
#    # timedatectl set-ntp true
#    # 
#    # # Set the hardware clock based on the system clock, however the HW clock
#    # # will be set in UTC.
#    # timedatectl set-local-rtc 0
#    # hwclock --systohc
#    # 
#    # # TODO: Password
#    # # TODO: Hostname
#    # # TODO: Root shell -> fish
#    # # TODO: Create nixpulvis user (fish shell)
#    # # TODO: Install dotfiles
